apiVersion: v1
kind: Service
metadata:
  name: {{ template "rest-api-mock.fullname" . }}
  labels:
    app: {{ template "rest-api-mock.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
    - port: {{ .Values.service.externalPort }}
      protocol: TCP
      targetPort: {{ .Values.service.internalPort }}
      name: http
  selector:
    app.kubernetes.io/name: {{ include "rest-api-mock.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: "{{ .Values.service.type }}"
