---
replicaCount: 1

image:
  repository: 079754108934.dkr.ecr.eu-central-1.amazonaws.com/riskwolf-ui
  tag: <buildNum>
  useImagePullSecrets: false

ingress:
  ingressClassName: nginx-internal
  annotations:
    cert-manager.io/cluster-issuer: shared
    external-dns.alpha.kubernetes.io/class: shared
  hosts:
    - host: staging.riskwolf.com
      paths: ["/"]
  tls:
    - secretName: staging.riskwolf.com
      hosts:
        - staging.riskwolf.com

configFile: config-staging.js
